### PR TITLE
Add operators to Byte and Bool

### PR DESCRIPTION
**Pull request by bernsteining**
Currently rune doesn't allow these bitwise operators on the `Byte` type:
* BitAnd (u8 & u8)
* BitAndAssign (u8 &= u8)
* BitXor (u8 ^ u8)
* BitXorAssign (u8 ^= u8)
* BitOr (u8 | u8)
* BitOrAssign (u8 |= u8)
* Shl (u8 << u8)
* ShlAssign (u8 <<= u8)
* Shr (u8 >> u8)
* ShrAssign (u8 >>= u8)

Also, rune doesn't allow these bitwise operators on the `Bool` type:
* BitAndAssign (bool &= bool)
* BitXorAssign (bool ^= bool)
* BitOrAssign (bool |= bool)

The following commit adds all these bitwise operators.

Then, following rune script can be run as expected:

```
pub fn main() {

    // byte ops
    let byte = 128u8;

    println!("byte & 1u8 {}", byte & 1u8);
    byte &= 1u8;
    println!("{}", byte);

    println!("byte ^ 1u8: {}", byte ^ 1u8);
    byte ^= 1u8;
    println!("{}", byte);

    println!("byte | 1u8: {}", byte | 1u8 );
    byte |= 1u8;
    println!("{}", byte);

    println!("byte << 1u8: {}", byte << 1u8);
    byte <<= 1u8;
    println!("{}", byte);

    println!("byte >> 1u8: {}", byte >> 1u8);
    byte >>= 1u8;
    println!("{}", byte);


    // bool ops
    let mybool = true;

    mybool &= true;
    println!("{}", mybool);

    mybool ^= true;
    println!("{}", mybool);

    mybool |= true;
    println!("{}", mybool);
}
```

### CODE REVIEW

**Comment by udoprog** [comment]
Build failure does not look like your fault. I'll check it out when I get a minute.

**Comment by udoprog** [comment]
The one part I'm missing is some tests in [`vm_arithmetic`](https://github.com/rune-rs/rune/blob/main/crates/rune/src/tests/vm_arithmetic.rs).

**Comment by bernsteining** [comment]
> The one part I'm missing is some tests in [`vm_arithmetic`](https://github.com/rune-rs/rune/blob/main/crates/rune/src/tests/vm_arithmetic.rs).

Indeed tests were missing, thanks for pointing where to write them. 

I added a few tests ([d10dbb5](https://github.com/rune-rs/rune/pull/655/commits/d10dbb5877a8eee8e361bc990f848e7435bbf366)) for `u8` ops in a rather verbose fashion since I'm not familiar with macros yet. 

I also wanted to test for `Underflow` and `Overflow` errors as follow:

```rust
error_test!(1u8 << 8 = Overflow);
error_test!(255u8 >> 8 = Underflow);
```

But the tests wouldn't pass as expected.

Writing these tests made me realise that shifting `u8` is way more natural with `i64` directly so [d10dbb5](https://github.com/rune-rs/rune/pull/655/commits/d10dbb5877a8eee8e361bc990f848e7435bbf366) takes care of that.

**Comment by udoprog** [comment]
Moved the tests to use `op_tests!` for better coverage (which had to be modified), and discovered that some assign ops did not use i64 as operand, so fixed that.

**Pull request merged**
