### PR TITLE
Support non-ASCII identifiers

### PR DESCRIPTION
**Pull request by lotem**
Support Unicode identifiers.

Refer to the similar language feature in Rust:
https://github.com/rust-lang/rfcs/pull/2457

### CODE REVIEW

**Comment by lotem** [comment]
Hi John-John @udoprog,

The `non_ascii_idents` feature is now merged to stable Rust. It would be nice to have Unicode identifier names in Rune too.
So far the feature seems to work after a few changes. Please advice if there's more to do.

**Comment by udoprog** [comment]
Hi!

This looks great, thanks for the PR!

Please move the test into `crates/rune/tests`. They will be picked up automatically there.

A cargo feature flag is not appropriate since it transiently changes the behavior of anyone using Rune if one dependency activates it. In my view we should just adopt this for 0.14. If we do think it's an apptopriate optional feature, add a an `Options` flag so that individual projects can decide themselves whether or not to activate it.

**Comment by lotem** [comment]
Thanks for the suggestions. I'll update the PR later.

**Comment by lotem** [comment]
I was worried about introducing a dependency for a rarely needed feature. Otherwise I don't think users will ever want to disable it since it's a compatible change. Also the performance report from `unicode-ident` seems to be less of a concern.

**Comment by udoprog** [comment]
The dependency is not a problem so please go ahead.

**Comment by udoprog** [comment]
Thank you!

**Pull request merged**
