### PR TITLE
Format Fixes

### PR DESCRIPTION
**Pull request by SWW13**
This pull requests fixes issue #684, #693 and #703 and adds multiple tests to ensure formatting works as expected.

I also tested against all rune files in the project to make sure no new regression is introduced.

### CODE REVIEW

**Comment by udoprog** [comment]
Hey, Thanks for fixing these!

Rebased since a new stable release happened with a few new changes.

Note that `nightly` is [expected to be broken](https://github.com/rust-lang/rust/issues/123748#issuecomment-2168055393) for now. It is just a canary.

**Comment by udoprog** [comment]
Got a legit test failure I've not dug into: https://github.com/rune-rs/rune/actions/runs/9517091651/job/26235234512?pr=710#step:6:1174

**Comment by SWW13** [comment]
That's due to this change: https://github.com/rune-rs/rune/pull/710/commits/2d4da8e335e343fe055ad44ce98ce8e3596482eb

Previously the trailing `/` was missing, so I assumed the span end must be after the char for it to be included.

**Comment by udoprog** [comment]
Very nice, thank you!

**Pull request merged**
